---
# defaults file for roles/vrising
vrising_service_directory: vrising
vrising_service_path: "{{ services_path_2 }}/{{ vrising_service_directory }}"
vrising_volume_persistentdata: "{{ vrising_service_path }}/volumes/persistentdata"
vrising_volume_server: "{{ vrising_service_path }}/volumes/server"
vrising_container_name: vrising
vrising_secure: "true"
vrising_password: ""
vrising_game_port: "9876"
vrising_query_port: "9877"
vrising_rcon_port: "9878"
vrising_rcon_enabled: "true"
vrising_max_connected_users: "8"
vrising_max_connected_admins: "4"
vrising_list_on_master_server: "false"
vrising_list_on_steam: "false"
vrising_list_on_eos: "false"
vrising_auto_save_count: "40"
vrising_auto_save_interval: "120"
vrising_game_settings_preset: StandardPvE
vrising_fps: 30
vrising_compress_save_files: "true"
