object IcingaDB "icingadb" {
  host = "127.0.0.1"
  username = "{{ valkey_user_icingadb }}"
  port = "{{ valkey_port }}"
  password = "{{ valkey_icingadb_password }}"
  db_index = {{ valkey_db_icingadb }}
}
