---
- name: ⚙️ Adds Caddy key
  ansible.builtin.copy:
    src: files/caddy-stable-archive-keyring.gpg
    dest: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    mode: "0644"
    owner: "root"
    group: "root"
  become: true

- name: ⚙️ Adds Caddy repo
  ansible.builtin.deb822_repository:
    repo: deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    state: present
  become: true

- name: 👤 Creates user
  ansible.builtin.user:
    state: present
    name: "{{ caddy_user }}"
    home: "{{ caddy_path }}"
    create_home: false
    append: true
    groups:
      - app
  become: true

- name: 📂 Creates paths
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ app_gid }}"
    mode: "0770"
  loop:
    - "{{ caddy_path }}"
    - "{{ caddy_sites }}"
  become: true
  become_user: "{{ caddy_user }}"

- name: 📦 Installs caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  become: true


- name: ⬆️ Pushes Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_caddyfile }}"
    mode: "0770"
    owner: "{{ caddy_user }}"
    group: "{{ app_gid }}"
  become: true
  become_user: "{{ caddy_user }}"
  notify: reload caddy
