/*
 * Icinga2 CheckCommand definition for check_memory monitoring plugin
 * See https://github.com/madrisan/nagios-plugins-linux/blob/main/contrib/icinga2/CheckCommands.conf
*/
{% raw %}
object CheckCommand "memory" {
	command = [ PluginDir + "/check_memory" ]

	arguments += {
		"--warning" = {
			description = "Warning threshold (e.g. '20%')"
			value = "$memory_warning$"
		}
		"--critical" = {
			description = "Critical threshold (e.g. '90%')"
			value = "$memory_critical$"
		}
		"--available" = {
			description = "display the free/available memory"
			set_if = "$memory_available$"
		}
		"--vmstats" = {
			description = "display the virtual memory perfdata"
			set_if = "$memory_vmstats$"
		}
		"--units" = {
		  description = "show output in the selected unit (default: KB), choose bytes, B, kB, MB, GB, KiB, MiB, GiB"
			value = "$memory_units$"
			set_if = {{ len(service.vars.memory_units) > 0 }}
		}
	}
}
{% endraw %}
