template Notification "mail" {
  command = "mail"

  types = [ Problem, Acknowledgement, Recovery, Custom,
            FlappingStart, FlappingEnd,
            DowntimeStart, DowntimeEnd, DowntimeRemoved ]

  vars += {
    notification_icingaweb2url = "https://{{ icinga_domain }}"
    // notification_from = "Monitoring <icinga@example.com>"
    notification_logtosyslog = false
  }

  period = "always"
}


apply Notification "mail" to Host {
  assign where host.vars.notification.mail
  import "mail"
  user_groups = host.vars.notification.mail.groups
  users = host.vars.notification.mail.users
}

apply Notification "mail" to Service {
  assign where host.vars.notification.mail
  import "mail"
  user_groups = host.vars.notification.mail.groups
  users = host.vars.notification.mail.users
}

