apply Service "CPU Load" {
  assign where true
  import "service"
  check_command = "load"
  icon_image = "microchip"
  vars.load_percpu = true
  vars.load_procs_to_show = 3
  vars.load_cload1 = 1.5
  vars.load_cload5 = 1.5
  vars.load_cload15 = 1
  vars.load_wload1 = 1
  vars.load_wload5 = 0.9
  vars.load_wload15 = 0.9
}

apply Service "Systemd" {
  assign where true
  import "service"
  icon_image = "gears"
  check_command  = "systemd"
  check_interval = 1d
  vars.systemd_dead_timers = true;
  vars.systemd_dead_timers_critical = "86400" # One Day
  vars += host.vars.systemd ? host.vars.systemd : {}
}

apply Service "Memory" {
  assign where true
  import "service"
  check_command = "mem"
  icon_image = "memory"
}


apply Service "Ping IPv4" {
  assign where host.vars.external_address.v4
  import "service"
  icon_image = "circle-nodes"
  check_command = "ping4"
  vars.ping4_hostname = host.vars.external_address.v6
}

apply Service "Ping IPv6" {
  assign where host.vars.external_address.v6
  import "service"
  icon_image = "circle-nodes"
  check_command = "ping6"
  vars.ping6_hostname = host.vars.external_address.v6
}

apply Service "SSH" {
  assign where (host.address || host.address6) && host.vars.sshd_port
  import "service"
  icon_image = "terminal"
  check_command = "ssh"
  vars.ssh_port = host.vars.sshd_port
}

apply Service for (endpoint => config in host.vars.http_endpoints) {
  import "service"
  check_command = "curl"
  vars += config
}

apply Service "Health " for (disk in host.vars.disks) {
  import "service"
  check_command = "check_smart"
  check_interval = 1d
  icon_image = "heart-pulse"
  vars.smart_device = disk
  vars.smart_interface = "auto"
  vars.smart_warn = "Reallocated_Sector_Ct=70,Current_Pending_Sector=62"
}

apply Service "Usage " for (storage => config in host.vars.storage) {
  import "service"
  check_command = "disk"
  icon_image = "circle-half-stroke"
  vars.disk_units = "GB"
  vars += config
}

apply Service "Icinga" {
 assign where host.name == NodeName
 import "service"
 check_command = "icinga"
}

apply Service "apt" {
  assign where host.vars.package_manager == "apt"
  import "service"
  check_interval = 1h
  check_command = "apt"
  icon_image = "cube"
}
