template Host "host" {
  max_check_attempts = 3
  check_interval = 1m
  retry_interval = 30s
  check_command = "hostalive"
}

template Service "service" {
  check_interval = 1m
  max_check_attempts = 5
  retry_interval = 10s
}
