object UserGroup "admin" {
  display_name = "Admins"
}

{% for admin in admins -%}
object User "{{ admin.name }}" {
  display_name = "{{ admin.name }}"
  groups = [ "admin" ]
  email = "{{ admin.email }}"
  {% if admin.xmpp is defined %}
  vars.xmpp = "{{ admin.xmpp }}"
  {% endif %}
}
{% endfor %}
