---
# tasks file for roles/minecraft
- name: 📂 Creates service path
  ansible.builtin.file:
    path: "{{ minecraft_service_path }}"
    state: directory
    mode: "0755"
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"
  become: true

- name: 📂 Creates volume
  ansible.builtin.file:
    path: "{{ minecraft_volume_data }}"
    state: directory
    mode: "0700"
    owner: "{{ app_uid }}"
    group: "{{ app_gid }}"
  become: true

- name: 🚀 Sets up cron job
  ansible.builtin.cron:
    name: "{{ minecraft_container_name }} reboot"
    minute: "0"
    hour: "6"
    job: "docker restart {{ minecraft_container_name }}"
    user: root
    state: present
  become: true

- name: 🚀 Starts container
  community.docker.docker_container:
    name: "{{ minecraft_container_name }}"
    image: itzg/minecraft-server:java17
    tty: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "25565:25565"
    env:
      EULA: "TRUE"
      UID: "{{ app_uid }}"
      GID: "{{ app_gid }}"
      MEMORY: "{{ minecraft_memory }}"
      TZ: "{{ ansible_date_time.tz }}"
      ENABLE_ROLLING_LOGS: "{{ minecraft_enable_rolling_logs }}"
      DIFFICULTY: "{{ minecraft_difficulty }}"
      SNOOPER_ENABLED: "false"
      SERVER_NAME: "{{ minecraft_server_name }}"
      CF_API_KEY: "{{ minecraft_curseforge_api_key }}"
      TYPE: "{{ minecraft_type }}"
      CF_PAGE_URL: "{{ minecraft_curseforge_page }}"
      FTB_MODPACK_ID: "{{ minecraft_ftb_modpack }}"
      ENABLE_AUTOPAUSE: "{{ minecraft_autopause }}"
      RCON_PASSWORD: "{{ minecraft_rcon_password }}"
      VERSION: "{{ minecraft_version }}"
      ENABLE_WHITELIST: "{{ minecraft_whitelist }}"
      ENFORCE_WHITELIST: "{{ minecraft_enforce_whitelist }}"
      JVM_OPTS: >-
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1HeapRegionSize=8M
        -XX:G1ReservePercent=20
        -XX:G1HeapWastePercent=5
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1
      EXISTING_WHITELIST_FILE: SKIP
      EXISTING_OPS_FILE: SKIP
    volumes:
      - "{{ minecraft_volume_data }}:/data"
