object Host "mantis" {
  import "host"

  address = "127.0.0.1"
  address6 = "::1"

  vars.sshd_port = "20615"
  vars.package_manager = "nix"
  vars.http_endpoints = {
    "dash.home.arpa" = {
      curl_vhost = "dash.home.arpa"
      curl_tls = true
      curl_expect_string = "200"
    }
    "id.home.arpa" = {
      curl_vhost = "id.home.arpa"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Immich" = {
      curl_vhost = "photos.home.arpa"
      curl_url = "/api/server/ping"
      curl_tls = true
      curl_expect_string = "200"
      curl_expect_content_string = "pong"
    }
    "Audiobookshelf" = {
      curl_vhost = "audiobooks.home.arpa"
      curl_url = "/audiobookshelf/login/"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Paperless" = {
      curl_vhost = "documents.home.arpa"
      curl_url = "/accounts/login/?next=/"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Moonraker" = {
      curl_vhost = "otacon.home.arpa"
      curl_url = "/machine/system_info"
      curl_tls = true
      curl_expect_string = "200"
      curl_expect_content_string = "\"instance_ids\":{\"moonraker\":\"moonraker\",\"klipper\":\"klipper\""
    }
    "AdGuard Webserver" = {
      curl_vhost = "dns.home.arpa/"
      curl_tls = true
      curl_expect_string = "200"
    }
  }

  vars.disks = [ "/dev/nvme0" ]
  vars.storage = {
    "/" = {
      disk_partitions = "/"
    }
  }

  vars.notification["mail"] = {
    users = [ "yuri" ]
  }

  vars.systemd = {
    systemd_critical = 150
    systemd_warning = 120
  }
}

template Service "adguard_dns" {
  import "service"
  check_command = "dns"
  host_name = "mantis"
  vars.dns_server = "127.0.0.1"
}

object Service "AdGuard Overrides home.arpa" {
  import "adguard_dns"
  vars.dns_lookup = "dash.home.arpa"
  vars.dns_expected_answers = "192.168.0.11"
}

object Service "AdGuard Blocks Ads" {
  import "adguard_dns"
  vars.dns_lookup = "static.doubleclick.net"
  vars.dns_expected_answers = "0.0.0.0,::"
}

object Service "AdGuard Resolves Upstream" {
  import "adguard_dns"
  vars.dns_lookup = "catboy.house"
  vars.dns_expected_answers = "46.4.241.139"
}

