object ApiUser "{{ icinga_api_root }}" {
  password = "{{ icinga_api_root_password }}"
  permissions = [ "*" ]
}

object ApiUser "{{ icinga_api_web }}" {
    password = "{{ icinga_api_web_password }}"
    permissions = [ "actions/*", "objects/modify/*", "objects/query/*", "status/query" ]
}
