object Host NodeName {
  import "host"

  display_name = "catboy.house"
  address = "127.0.0.1"
  address6 = "::1"

  vars.package_manager = "apt"
  vars.external_address = {
    v4 = "catboy.house"
    v6 = "catboy.house"
  }
  vars.sshd_port = "{{ sshd_port }}"
  vars.http_endpoints = {
    "Authelia" = {
      curl_vhost = "auth.catboy.house"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Docmost" = {
      curl_vhost = "wiki.catboy.house"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Icinga Web" = {
      curl_vhost = "{{ icinga_domain }}"
      curl_tls = true
      curl_expect_string = "302"
    }
    "id.catboy.house" = {
      curl_vhost = "id.catboy.house"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Jellyfin" = {
      curl_vhost = "jellyfin.catboy.house"
      curl_tls = true
    }
    "Jellyseerr" = {
      curl_vhost = "jellyseerr.catboy.house"
      curl_tls = true
      curl_url = "/login"
      curl_expect_string = "200"
    }
    "Mealie" = {
      curl_vhost = "mealie.catboy.house"
      curl_tls = true
    }
    "Nextcloud" = {
      curl_vhost = "cloud.catboy.house"
      curl_tls = true
    }
    "RomM" = {
      curl_vhost = "{{ romm_domain }}"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Wakapi" = {
      curl_vhost = "wakapi.catboy.house"
      curl_tls = true
      curl_url = "/login"
      curl_expect_string = "200"
    }
    "Woodpecker" = {
      curl_vhost = "ci.catboy.house"
      curl_tls = true
      curl_url = "/login"
      curl_expect_string = "200"
    }
    "Yamtrack" = {
      curl_vhost = "track.catboy.house"
      curl_tls = true
      curl_url = "/accounts/login/?next=/"
      curl_expect_string = "200"
    }
  }

  vars.disks = [
    "/dev/sda",
    "/dev/sdb",
    "/dev/sdc",
    "/dev/sdd",
    "/dev/sde",
    "/dev/sdf",
    "/dev/sdg",
    "/dev/sdh",
    "/dev/sdi",
    "/dev/sdj"
  ];
  vars.storage = {
    "/" = {
      disk_partitions = "/"
    }
    "/home" = {
      disk_partitions = "/home"
    }
  }

  vars.systemd = {
    systemd_critical = 500
    systemd_warning = 400
  }

  vars.notify.groups = [ "admin" ]
}
