template Host "generic-host" {
  max_check_attempts = 3
  check_interval = 1m
  retry_interval = 30s
  check_command = "hostalive"
}

object Host NodeName {
  import "generic-host"

  address = "127.0.0.1"
  address6 = "::1"

  vars.external_address = {
    v4 = "catboy.house"
    v6 = "catboy.house"
  }
  vars.sshd_port = "{{ sshd_port }}"
  vars.http_endpoints = {
    "Icinga Web" = {
      curl_vhost = "{{ icinga_domain }}"
      curl_tls = true
      curl_expect_string = "302"
    }
    "id.catboy.house" = {
      curl_vhost = "id.catboy.house"
      curl_tls = true
      curl_expect_string = "200"
    }
    "Jellyfin" = {
      curl_vhost = "jellyfin.catboy.house"
      curl_tls = true
    }
    "Nextcloud" = {
      curl_vhost = "cloud.catboy.house"
      curl_tls = true
    }
    "RomM" = {
      curl_vhost = "{{ romm_domain }}"
      curl_tls = true
      curl_expect_string = "200"
    }
  }

  vars.disks = [
    "/dev/sda",
    "/dev/sdb",
    "/dev/sdc",
    "/dev/sdd",
    "/dev/sde",
    "/dev/sdf",
    "/dev/sdg",
    "/dev/sdh",
    "/dev/sdi",
    "/dev/sdj"
  ];

  vars.notification["mail"] = {
    groups = [ "admin" ]
  }
}
