template Service "generic-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
}

object ServiceGroup "ping" {
  display_name = "Reachable"
}

object ServiceGroup "disk" {
  display_name = "Disks"
}

object ServiceGroup "http" {
  display_name = "Services"
}

apply Service "Ping IPv4" {
  assign where host.vars.external_address.v4
  import "generic-service"
  check_command = "ping4"
  groups = [ "ping" ]
  vars.ping4_hostname = host.vars.external_address.v6
}

apply Service "Ping IPv6" {
  assign where host.vars.external_address.v6
  import "generic-service"
  check_command = "ping6"
  groups = [ "ping" ]
  vars.ping6_hostname = host.vars.external_address.v6
}

apply Service "SSH" {
  assign where (host.address || host.address6) && host.vars.sshd_port
  import "generic-service"
  check_command = "ssh"
  vars.ssh_port = host.vars.sshd_port
}

apply Service for (endpoint => config in host.vars.http_endpoints) {
  import "generic-service"
  groups = [ "http" ]
  check_command = "curl"
  vars += config
}

apply Service for (disk in host.vars.disks) {
  import "generic-service"
  groups = [ "disk" ]
  check_command = "check_smart"
  check_interval = 1d
  vars.smart_device = disk
  vars.smart_interface = "auto"
  vars.smart_warn = "Reallocated_Sector_Ct=70,Current_Pending_Sector=62"
}

apply Service "Icinga" {
 assign where host.name == NodeName
 import "generic-service"
 check_command = "icinga"
}

apply Service "Packages" {
  assign where host.name == NodeName
  import "generic-service"
  check_interval = 1h
  check_command = "apt"
}
