---
# handlers file for roles/nextcloud
- name: 🚀 Restarts OnlyOffice
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_service_path }}"
    services:
      - onlyoffice
    state: restarted
  listen: restart onlyoffice
