const PluginDir = "/usr/lib/nagios/plugins"
const ManubulonPluginDir = "/usr/lib/nagios/plugins"
const PluginContribDir = "/usr/lib/nagios/plugins"
const NodeName = "catboy-house"
const ZoneName = "master"
const TicketSalt = "{{ icinga_ticket_salt }}"
const IcingaWebUrl = "https://{{icinga_domain}}"
