object Endpoint NodeName { }

object Zone ZoneName {
  endpoints = [ NodeName ]
}

object Endpoint "mantis" { }

object Zone "mantis" {
  parent = "master"
  endpoints = ["mantis"]
}

object Endpoint "bundestag-gmbh" { }

object Zone "bundestag-gmbh" {
  parent = "master"
  endpoints = ["bundestag-gmbh"]
}

object Zone "global" {
  global = true
}
