object Endpoint "catboy-house" {
}

object Zone "master" {
        endpoints = [ "catboy-house" ]
}

object Zone "global-templates" {
        global = true
}

object Zone "director-global" {
        global = true
}
