---
# tasks file for roles/sabnzbd
- name: 📂 Creates service path
  ansible.builtin.file:
    path: "{{ sabnzbd_service_path }}"
    state: directory
    mode: "0755"

- name: 📂 Crates volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: 1000
    group: 100
  loop:
    - "{{ downloads_path }}"
    - "{{ downloads_path }}/incomplete"
    - "{{ sabnzbd_volume_config }}"

- name: 🚀 Starts container
  community.docker.docker_container:
    name: "{{ sabnzbd_container_name }}"
    image: linuxserver/sabnzbd:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ docker_gateway }}:{{ sabnzbd_service_port }}:8080"
    volumes:
      - "{{ downloads_path }}:/downloads"
      - "{{ downloads_path }}/incomplete:/incomplete-downloads"
      - "{{ sabnzbd_volume_config }}:/config"
