object Host "bundestag-gmbh" {
  import "host"
  display_name = "bundestag.gmbh"
  address = "127.0.0.1"
  address6 = "::1"

  vars.sshd_port = "51312"
  vars.package_manager = "nix"
  vars.external_address = {
    v4 = "bundestag.gmbh"
    v6 = "bundestag.gmbh"
  }
  vars.http_endpoints = {
    "Matrix" = {
      curl_vhost = "bundestag.gmbh"
      curl_url = "/.well-known/matrix/server"
      curl_tls = true
      curl_expect_string = "200"
      curl_expect_content_string = "{\"m.server\":\"bundestag.gmbh:443\"}"
    }
    "Livekit" = {
      curl_vhost = "livekit.bundestag.gmbh"
      curl_url = "/"
      curl_tls = true
      curl_expect_string = "200"
    }
  }

  vars.storage = {
    "/" = {
      disk_partitions = "/"
    }
    "/mount/external" = {
      disk_partitions = "/mount/external"
    }
  }

  vars.notify.users = ["yuri"]

  vars.systemd = {
    systemd_critical = 150
    systemd_warning = 120
  }
}
