---
# defaults file for roles/grafana
grafana_container_name: grafana
grafana_service_directory: grafana
grafana_service_path: "{{ services_path_2 }}/{{ grafana_service_directory }}"
grafana_volume_data: "{{ grafana_service_path }}/volumes/data"
grafana_user_name: grafana
grafana_smtp_from_name: "Grafana"