---
# defaults file for roles/grafana
grafana_container_prefix: grafana
grafana_grafana_container_name: "{{ grafana_container_prefix }}-grafana"
grafana_loki_container_name: "{{ grafana_container_prefix }}-loki"
grafana_promtail_container_name: "{{ grafana_container_prefix }}-promtail"
grafana_service_directory: grafana
grafana_service_path: "{{ services_path_2 }}/{{ grafana_service_directory }}"
grafana_volume_data: "{{ grafana_service_path }}/volumes/data"
grafana_volume_loki_config: "{{ grafana_service_path }}/volumes/loki-config"
grafana_volume_promtail_config: "{{ grafana_service_path }}/volumes/promtail-config"
grafana_user_name: grafana
grafana_smtp_from_name: "Grafana"