---
# tasks for pocket-id
- name: 👤 Creates user
  ansible.builtin.user:
    state: present
    name: "{{ pocketid_user }}"
    uid: "{{ pocketid_uid }}"
    create_home: true
    home: "{{ pocketid_path }}"
    groups:
      - "{{ app_gid }}"
  become: true

- name: 👤 Creates database
  community.postgresql.postgresql_db:
    name: "{{ pocketid_db }}"

- name: 👤 Creates extensions on database
  community.postgresql.postgresql_ext:
    login_db: "{{ pocketid_db }}"
    name: "{{ item }}"
  loop:
    - citext
    - pgcrypto

- name: 👤 Creates database user
  community.postgresql.postgresql_user:
    login_db: "{{ pocketid_db }}"
    name: "{{ pocketid_user }}"
    password: "{{ pocketid_db_password }}"

- name: 👤 Grants privileges to user
  community.postgresql.postgresql_privs:
    login_db: "{{ pocketid_db }}"
    roles: "{{ pocketid_user }}"
    grant_option: false
    type: schema
    obj: public
    privs: ALL

- name: 📂 Creates volume
  ansible.builtin.file:
    state: directory
    path: "{{ pocketid_volume_data }}"
    mode: "0700"
  become: true
  become_user: "{{ pocketid_user }}"

- name: 🚀 Starts Container
  community.docker.docker_container:
    state: started
    name: "{{ pocketid_container }}"
    hostname: "{{ pocketid_hostname }}"
    image: ghcr.io/pocket-id/pocket-id:v2
    restart_policy: unless-stopped
    user: "{{ pocketid_uid }}:{{ app_gid }}"
    ports:
      - "{{ docker_gateway }}:{{ pocketid_port }}:1411"
    volumes:
      - "{{ pocketid_volume_data }}:/app/data"
    networks:
      - name: "{{ postgres_network }}"

    env:
      ACCENT_COLOR: "#7287fd"
      ANALYTICS_DISABLED: "true"
      ALLOW_USER_SIGNUPS: withToken
      APP_NAME: "catboy.house account~"
      APP_URL: "{{ pocketid_url }}"
      DB_CONNECTION_STRING: "{{ pocketid_db_connection }}"
      EMAILS_VERIFIED: "true"
      EMAIL_API_KEY_EXPIRATION_ENABLED: "true"
      EMAIL_LOGIN_NOTIFICATION_ENABLED: "true"
      EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: "false"
      EMAIL_ONE_TIME_ACCESS_AS_UNAUTHENTICATED_ENABLED: "true"
      ENCRYPTION_KEY: "{{ pocketid_encryption_key }}"
      HOME_PAGE_URL: "/settings/apps"
      MAXMIND_LICENSE_KEY: "{{ maxmind_api_key }}"
      PGID: "{{ app_gid }}"
      PUID: "{{ pocketid_uid }}"
      REQUIRE_USER_EMAIL: "false"
      SESSION_DURATION: "43200" # 30  days
      SMTP_FROM: "{{ auth_smtp_user }}"
      SMTP_HOST: "{{ smtp_server }}"
      SMTP_PASSWORD: "{{ auth_smtp_password }}"
      SMTP_PORT: "{{ smtp_port }}"
      SMTP_TLS: starttls
      SMTP_USER: "{{ auth_smtp_user }}"
      TRUST_PROXY: "true"
      UI_CONFIG_DISABLED: "true"
      WEBAUTHN_USER_VERIFICATION: "preferred"
      WEBAUTHN_ALLOW_SYNCED_PASSKEYS: "true"
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

- name: ⬆️ Pushes Caddy config
  ansible.builtin.template:
    src: pocketid.caddy.j2
    dest: "{{ caddy_sites }}/pocketid.caddy"
    mode: "0770"
    group: "{{ app_gid }}"
  notify: reload caddy
