---
terraria_service_path: "{{ services_path_2 }}/{{ terraria_service_directory }}"
terraria_sources: "{{ terraria_service_path }}/src"
terraria_volume_world: "{{ terraria_service_path }}/volumes/world"
terraria_container_name: terraria
terraria_port: 7777
terraria_world_name: Terranya
terraria_image_name: catboy-house/terraria
terraria_tshock_version: 5.2.4
terraria_build_cronjob_name: "{{ terraria_image_name }}"
