---
# handlers file for roles/monitoring
- name: 🚀 Restarts Promtail
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_service_path }}"
    services:
      - promtail
    state: restarted
  listen: restart promtail

- name: 🚀 Restarts Prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_service_path }}"
    services:
      - prometheus
    state: restarted
  listen: restart prometheus
