---
- name: Administration
  hosts: all
  vars:
    ansible_python_interpreter: "{{ play_venv }}/bin/pyenv"
  roles:
    - dotfiles
    - watchtower
    - role: portainer
      vars:
        portainer_service_port: 27949
