---
- name: Services
  hosts: all
  vars:
    ansible_python_interpreter: "{{ play_venv }}/bin/pyenv"
  roles:
    - role: seafile
      vars:
        seafile_service_port: 28947
        seafile_volume_data: /home/seafile/data
        seafile_volume_db: /home/seafile/db

    - role: linkding
      vars:
        linkding_service_port: 28948

    - role: mealie
      vars:
        mealie_domain: mealie.catboy.house
        mealie_service_port: 28949

    - role: tinfoil_store
      vars:
        tinfoil_store_service_port: 29157

    - role: pyload
      vars:
        pyload_service_port: 29158

    - role: jellyfin
      vars:
        jellyfin_service_port: 30212

    - role: jellyseerr
      vars:
        jellyseerr_service_port: 30213

    - role: seedbox
      vars:
        seedbox_webui_port: 30214

    - role: arr
      tags: arr
      vars:
        arr_sonarr_port: 30215
        arr_radarr_port: 30216
        arr_prowlarr_port: 30217

    - role: sabnzbd
      tags: sabnzbd
      vars:
        sabnzbd_service_port: 30218
