---
- name: Services
  hosts: all
  vars:
    ansible_python_interpreter: "{{ play_venv }}/bin/pyenv"
  roles:
    - role: linkding
      vars:
        linkding_service_port: 8948
        linkding_service_directory: linkding

    - role: mealie
      vars:
        mealie_domain: mealie.catboy.house
        mealie_service_port: 8949
        mealie_service_directory: mealie

    - role: tinfoil_store
      vars:
        tinfoil_store_service_port: 29157
        tinfoil_store_service_directory: tinfoil-store