---
# tasks file for roles/owncloud
- name: 👤 Creates user
  ansible.builtin.user:
    state: present
    name: "{{ owncloud_user_name }}"
    uid: "{{ owncloud_uid }}"
    create_home: false
    group: "{{ app_gid }}"
  become: true

- name: 📂 Creates volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "700"
    owner: "{{ owncloud_uid }}"
    group: "{{ app_gid }}"
  loop:
    - "{{ owncloud_volume_config }}"
    - "{{ owncloud_volume_data }}"
  become: true

- name: ⬆️ Pushes Caddy config
  ansible.builtin.template:
    src: owncloud.caddy.j2
    dest: "{{ caddy_sites }}/owncloud.caddy"
    mode: "0770"
    group: "{{ app_gid }}"
  notify: reload caddy

- name: 🚀 Starts container
  community.docker.docker_container:
    name: "{{ owncloud_container_name }}"
    image: owncloud/ocis
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ docker_gateway }}:{{ owncloud_service_port }}:9200"
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    env:
      OCIS_INSECURE: "false"
      OCIS_URL: "https://{{ owncloud_domain }}"
      PROXY_HTTP_ADDR: "0.0.0.0:9200"
      PROXY_TLS: "false"
      OCIS_LOG_LEVEL: "debug"
      OCIS_ADD_RUN_SERVICES: "notifications"
      NOTIFICATIONS_SMTP_HOST: "{{ smtp_server }}"
      NOTIFICATIONS_SMTP_PORT: "{{ smtp_port }}"
      NOTIFICATIONS_SMTP_SENDER: "{{ owncloud_smtp_sender }}"
      NOTIFICATIONS_SMTP_USERNAME: "{{ owncloud_smtp_user }}"
      NOTIFICATIONS_SMTP_PASSWORD: "{{ owncloud_smtp_password }}"
      NOTIFICATIONS_SMTP_INSECURE: "false"
    user: "{{ owncloud_uid }}:{{ app_gid }}"
    volumes:
      - "{{ owncloud_volume_config }}:/etc/ocis"
      - "{{ owncloud_volume_data }}:/var/lib/ocis"

